FROM ubuntu:latest
RUN apt-get update -y && apt-get upgrade -y && apt-get install openjdk-8-jdk wget
RUN mkdir /usr/local/tomcat
RUN wget https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.94/bin/apache-tomcat-8.5.94.tar.gz
RUN cd /tmp && tar xvfz apache-tomcat-8.5.94.tar.gz && cp -Rv /tmp/apache-tomcat-8.5.94/* /usr/local/tomcat
EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run
